from __future__ import annotations

import argparse
import json
import time
from datetime import datetime, timezone
from pathlib import Path

import duckdb


TABLES = {
    "film_study_tags": "film_study_tags.csv",
    "film_study_events_enriched": "film_study_events_enriched.csv",
    "film_study_possessions": "film_study_possessions.csv",
    "film_study_match_features": "film_study_match_features.csv",
    "film_study_zone_summary": "film_study_zone_summary.csv",
    "film_study_event_transitions": "film_study_event_transitions.csv",
    "film_study_data_dictionary": "film_study_data_dictionary.csv",
}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Load local film-study CSV outputs into a dedicated DuckDB database."
    )
    parser.add_argument(
        "--input-dir",
        default=str(repo_root() / "data" / "processed" / "film_study"),
        help="Directory containing film-study processed CSV outputs.",
    )
    parser.add_argument(
        "--db-path",
        default=str(repo_root() / "data" / "processed" / "film_study.duckdb"),
        help="Path to the target DuckDB database file.",
    )
    parser.add_argument(
        "--clips-csv",
        default=str(repo_root() / "data" / "private" / "clips" / "film_study_clips.csv"),
        help="Optional clip manifest CSV generated by extract_film_study_clips.py.",
    )
    parser.add_argument(
        "--retry-seconds",
        type=float,
        default=5.0,
        help="Retry window when the DuckDB file is temporarily locked by another process.",
    )
    return parser.parse_args()


def connect_with_retry(db_path: Path, retry_seconds: float) -> duckdb.DuckDBPyConnection:
    deadline = time.time() + max(0.0, retry_seconds)
    last_error: Exception | None = None
    while True:
        try:
            return duckdb.connect(str(db_path))
        except duckdb.IOException as err:
            last_error = err
            if time.time() >= deadline:
                raise
            time.sleep(0.5)


def main() -> None:
    args = parse_args()
    input_dir = Path(args.input_dir).expanduser().resolve()
    db_path = Path(args.db_path).expanduser().resolve()
    db_path.parent.mkdir(parents=True, exist_ok=True)

    con = connect_with_retry(db_path, args.retry_seconds)
    try:
        loaded_tables = {}
        for table_name, file_name in TABLES.items():
            csv_path = input_dir / file_name
            if not csv_path.exists():
                continue
            con.execute(
                f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM read_csv_auto(?, HEADER=TRUE)",
                [str(csv_path)],
            )
            row_count = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
            loaded_tables[table_name] = {
                "csv_path": str(csv_path),
                "rows": int(row_count),
            }

        clips_csv = Path(args.clips_csv).expanduser().resolve()
        if clips_csv.exists():
            csv_path = clips_csv
            con.execute(
                "CREATE OR REPLACE TABLE film_study_clips AS SELECT * FROM read_csv_auto(?, HEADER=TRUE)",
                [str(csv_path)],
            )
            row_count = con.execute("SELECT COUNT(*) FROM film_study_clips").fetchone()[0]
            loaded_tables["film_study_clips"] = {"csv_path": str(csv_path), "rows": int(row_count)}

        con.execute(
            """
            CREATE OR REPLACE VIEW vw_film_study_event_flow AS
            SELECT
              e.match_key,
              e.event_index,
              e.event_type,
              e.team_inferred,
              e.player,
              e.time_seconds,
              e.x_zone,
              e.y_lane,
              e.next_event_type,
              p.possession_id,
              p.possession_duration_seconds
            FROM film_study_events_enriched e
            LEFT JOIN film_study_possessions p
              ON e.match_key = p.match_key
             AND e.possession_id = p.possession_id
            """
        )
        con.execute(
            """
            CREATE OR REPLACE VIEW vw_film_study_match_rollup AS
            SELECT
              m.*,
              COALESCE(c.clip_count, 0) AS extracted_clip_count
            FROM film_study_match_features m
            LEFT JOIN (
              SELECT match_key, COUNT(*) AS clip_count
              FROM film_study_clips
              GROUP BY match_key
            ) c
              ON m.match_key = c.match_key
            """
        )

        metadata = {
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "db_path": str(db_path),
            "input_dir": str(input_dir),
            "loaded_tables": loaded_tables,
            "views": [
                "vw_film_study_event_flow",
                "vw_film_study_match_rollup",
            ],
        }
        metadata_path = input_dir / "film_study_duckdb_metadata.json"
        metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

        print(f"DuckDB ready: {db_path}")
        print(f"Wrote {metadata_path}")
    finally:
        con.close()


if __name__ == "__main__":
    main()
